### ISSUE TITLE
Score resets cause scoring errors

### ISSUE THREAD

**Issue by dudeofawesome** [Virginity-Bot/virginity-bot#54]
![image](https://user-images.githubusercontent.com/1683595/215910536-cc3a5577-f3b7-4704-bd5d-ff7a5d24790d.png)

I might have been in Discord at the time of the reset.

**Comment by EdgarSaldivar** [comment]
Not properly storing last reset time in the database.

**Comment by dudeofawesome** [comment]
I think this might have been a one-off thing. Haven't been able to repro since.
